  zbx_ln_rpm: "https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-agent-4.0.39-1.el7.x86_64.rpm"
  ln_zbx_srv: 127.0.0.1
  ansible_host: 0.0.0.0
  
  zbx_win_msi: "https://cdn.zabbix.com/zabbix/binaries/stable/6.2/6.2.0/zabbix_agent-6.2.0-windows-amd64-openssl.msi"
  zbx_file: "zabbix_agent-6.2.0-windows-amd64-openssl.msi"
  win_zabbix_server: 127.0.0.1
  win_listenport: 10050
  win_listen_ip: 0.0.0.0
  win_zabbix_server_active: 127.0.0.1